# Generated by Django 5.1.2 on 2024-11-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('cor', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('com_quem', models.CharField(blank=True, max_length=100, null=True)),
                ('informacoes', models.TextField(blank=True, max_length=500, null=True)),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendario.etiqueta')),
            ],
        ),
    ]
