# Generated by Django 5.1.2 on 2024-11-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Proprio', 'Próprio'), ('Alugado', 'Alugado')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('status_disponibilidade', models.BooleanField(default=True)),
                ('data_aquisicao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitaCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100)),
                ('solicitante', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('data_saida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.veiculo')),
            ],
        ),
    ]
