# Generated by Django 5.1.2 on 2024-11-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='numero_protocolo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
